#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

for script in $(find src/main -type f -name '*.xsl' -print); do
    if [[ ! $(basename $script) = 'standalone-functions.xsl' ]]; then
	sed -i -e 's/contains-token/fp:contains-token/g' $script
    fi
done


